services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8085:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - twir-dev

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    command: postgres -c max_connections=500
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '54321:5432'
    environment:
      POSTGRES_USER: twir
      POSTGRES_PASSWORD: twir
      POSTGRES_DB: twir
    networks:
      - twir-dev

  pgbouncer:
    image: bitnami/pgbouncer:1.23.1
    restart: unless-stopped
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_USERNAME=twir
      - POSTGRESQL_PASSWORD=twir
      - POSTGRESQL_DATABASE=twir

      - PGBOUNCER_AUTH_USER=twir
      - PGBOUNCER_DATABASE=twir
      - PGBOUNCER_MIN_POOL_SIZE=20
      - PGBOUNCER_MAX_CLIENT_CONN=4000
    networks:
      - twir-dev
    ports:
      -  '6432:6432'

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    command: dragonfly --dir /data/snapshots --dbfilename twir-redis-snapshot-{timestamp} --snapshot_cron "0 0 * * *"
    restart: always
    ports:
      - '6385:6379'
    volumes:
      - redis-data:/data
    networks:
      - twir-dev

  language-detector:
    image: ghcr.io/twirapp/language-detector:latest
    restart: always
    ports:
      - '3012:3012'
    environment:
      - APP_ENV=development

  tts:
    image: aculeasis/rhvoice-rest
    restart: always
    ports:
      - '7001:8080'
    networks:
      - twir-dev

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - '8000:9000'
      - '8090:9090'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-password
    volumes:
      - minio-data:/data

  temporal:
    image: temporalio/auto-setup:1.22.2
    restart: always
    depends_on:
      - postgres
    environment:
      - DB=postgresql
      - DB_PORT=5432
      # this is db addr
      - POSTGRES_SEEDS=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=twir
      - POSTGRES_PWD=twir
      - POSTGRES_DB=temporal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - ./configs/temporal:/etc/temporal/config/dynamicconfig
    networks:
      - twir-dev
    ports:
      - '7233:7233'
    labels:
      kompose.volume.type: configMap

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.2
    restart: always
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - twir-dev
    stdin_open: true
    tty: true

  temporal-ui:
    image: temporalio/ui:2.21.0
    restart: always
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - twir-dev
    ports:
      - '7234:8080'

  nats:
    image: nats:2.10.11-scratch
    command: -js -m 8222
    restart: always
    ports:
      - '4222:4222'
      - '8222:8222'
    networks:
      - twir-dev

volumes:
  redis-data:
  postgres-data:
  minio-data:

networks:
  twir-dev:
    driver: bridge
